# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"http://{default}/":
    type: upstream
    upstream: "drupal:php"

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"
