# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysql:
    type: "mysql:10.0"
    disk: 1250
drupal6:
    type: "mysql:10.0"
    disk: 1250
#
#redis:
#    type: "redis:3.0"
#
#solr:
#    type: "solr:4.10"
#    disk: 1024
